name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
        python-version:
          - "3.10"
          - "3.11"

    env:
      OE_LICENSE: ${{ github.workspace }}/oe_license.txt

    steps:
    - uses: actions/checkout@v4

    - name: Set up conda environment
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: devtools/env.yaml
        create-args: >-
          python=${{ matrix.python-version }}

    - name: Install package
      run: python -m pip install -e .

    - name: Install and license OpenEye Toolkits
      run: |
        echo "${SECRET_OE_LICENSE}" > ${OE_LICENSE}
        python -c "from openeye import oechem; assert oechem.OEChemIsLicensed()"
      env:
        SECRET_OE_LICENSE: ${{ secrets.OE_LICENSE }}

    - name: Run tests
      run: |
        vfgenerate.py _tests/data/config.yaml
